version: "3.3"

services:
  volunteerapi:
    build: 
      context: .
      dockerfile: Dockerfile
    # command: gunicorn activity_enrollment.wsgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network:
    external: true