version: "3.3"

services:
  volunteerapi:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network:
    external: true