# Generated by Django 3.1.1 on 2023-09-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='No_Show_Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_show_num', models.IntegerField(default=0)),
                ('semester', models.CharField(default='', max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sservice.student')),
            ],
        ),
    ]
