# Generated by Django 4.1.7 on 2023-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sservice", "0002_no_show_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="num_of_spots",
            field=models.IntegerField(default=0),
        ),
    ]
