# Generated by Django 3.1.1 on 2023-10-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sservice', '0003_activity_num_of_spots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='no_show_records',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student_activity_enrollment',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='student_activity_enrollment',
            old_name='student_id',
            new_name='student',
        ),
    ]
