# Generated by Django 4.2.5 on 2023-10-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sservice", "0005_auto_20231005_0959"),
    ]

    operations = [
        migrations.DeleteModel(name="No_Show_Records",),
    ]
