# Generated by Django 4.2.5 on 2023-10-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sservice", "0006_delete_no_show_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="No_Show_Records",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sservice.activity",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sservice.student",
                    ),
                ),
            ],
        ),
    ]
